README.md, jwt/__init__.py, tests/test_jwt.py
=> allow datetime.timedelta for leeway arg

jwt/__init__.py
...and only use the current implementation as a fallback.
Fixes #63.
=> Use constant time string comparison routine from hmac module

jwt/__init__.py, tests/test_jwt.py
The spec at http://self-issued.info/docs/draft-ietf-oauth-json-web-token.html#audDef states:
> The aud (audience) claim identifies the recipients that the JWT is intended for. Each principal intended to process the JWT MUST identify itself with a value in the audience claim. If the principal processing the claim does not identify itself with a value in the aud claim when this claim is present, then the JWT MUST be rejected.
As I understand it, Pyjwt doesn't seem to implement this requirement correctly. Basically it reverses the checks. Let me explain.
Pyjwt only checks the audience claim when an `audience=...` arg was specified to `decode()`, meaning that any `audience` claim in the JWT is blindly ignored if no such arg was passed. This results in the JWT bein  accepted, instead of being …
=> Invalid validation of audience claim

jwt/__init__.py, jwt/algorithms.py, jwt/utils.py, setup.py, tests/test_jwt.py
Algorithm-specific logic has been moved to the algorithms module and refactored into classes to make it a bit easier for others to add new standard or non-standard algorithms to the library.
Things to note:
* The public APIs (`jwt.encode()` and `jwt.decode()`) are completely unchanged
* `jwt.register_algorithm()` has been added to the public API for extensibility
* Crypto code that formally resided in `signing_methods`, `verify_methods`, and `prepare_key_methods` lists / functions has been rearranged into classes in `algorithms.py`. The sign, verify, and prepare_key methods are all nearly identical to their original versions.
=> Fixes #70. Implemented registry pattern for class-based algorithms

.travis.yml, tox.ini
I was looking at the builds in Travis and noticed two things that looked odd:
First, the version number listed under the Python column was "2.7" for all of our builds. This is misleading and is caused by the `python: 2.7` directive in the Travis configuration.
Second, the cryptography-related tests were being skipped on ALL of the builds!
I fixed the first part by removing the python version directive from travis.yml.
The second problem was caused by the fact that coverage was being installed as part of the travis config so whenever coverage was being executed by tox, it was being invoked using the Travis-provided Python interpreter and therefore ignored the virtual environment that tox created. Installing coverage as part of the tox.ini seems to have solved that problem. 
(Bonus: This …
=> Test improvements

jwt/api.py
The header function isn't a public part of the API, is not covered by any tests, and really doesn't seem to serve a practical purpose so I propose removing it.
=> Removed `api.header`

jwt/algorithms.py, jwt/api.py, tests/test_jwt.py
The [JWS spec](https://tools.ietf.org/html/draft-ietf-jose-json-web-signature-41#section-4.1.1) says: "The "alg" value is a case-sensitive ASCII string containing a StringOrURI value."
Our implementation currently normalizes case of the alg by uppercasing on decode. This PR resolves that behavior so that, by default, "none" is valid and "NONE" is not. Tests are added as well.
This PR also fixes a small bug with signature verification on the NoneAlgorithm related to the fact the `verify()` method is missing a parameter (whoops!)
=> Fix alg header parameter case sensitivity

MANIFEST.in
These are also nice to have.  :)
Cheers!
=> Include test stuff.

setup.cfg, tox.ini
This PR adds the proper max-line-length option to the setup.cfg where it will apply in Tox and in the normal CLI.
Right now, the max-line-length option for flake8 is in the tox.ini which makes it apply when the flake8 tox task is run.
However, when running flake8 locally from the CLI, you must specify the "--max-line-length" parameter in order for it to apply.
With the proposed change, `flake8 .` works the same in both environments.
=> Moved flake8 max-line-length option from tox.ini to setup.cfg so that it works when running flake8 from normal CLI as well.

README.md
* Added an FAQ section to the README with some text explaining how to extract public / private keys from a x509 certificate since we seem to get this question a lot.
* Moved "Tests" higher up so that Installation, Usage, and Tests are all grouped together.
* Wrapped a couple long lines in the existing README
=> Resolved #93 by adding a section the README detailing how to extract public / private keys from an x509 certificate.

.travis.yml, jwt/algorithms.py, jwt/contrib/algorithms/py_ecdsa.py, jwt/contrib/algorithms/pycrypto.py, tests/contrib/test_algorithms.py, tests/test_algorithms.py, tests/utils.py, tox.ini
This PR takes care of a chunk of the work towards resolving #99. Specifically, it accomplishes two things:
- Support for PyCrypto-based RSA and ecdsa-based EC signatures is restored in the `jwt.contrib.algorithms` module
- Each of the preferred `jwt.algorithms` as well as the `jwt.contrib.algorithms` now have static class variables for SHA256, SHA384, and SHA512 to make our default registration code a little simpler (it no longer has to know the specifics about the hash objects). This also could eventually allow us to write some shared test code between the preferred and `jwt.contrib.algorithms` algorithms.
This PR would allow a consumer to call register_algorithm and pass in the `RSAAlgorithm` or the `ECAlgorithm` from `jwt.contrib.algorithms` if they would like to use the legacy …
=> Back from the dead: PyCrypto and ECDSA

README.md, jwt/__init__.py, jwt/algorithms.py, jwt/api.py, jwt/exceptions.py, tests/test_api.py
Added an argument on the PyJWT object and on the `decode` method to allow a list of valid values for `alg` to be specified. The value specified in the `decode` method overrides the value for the PyJWT object. In addition, registering and unregistering algorithms adds and removes (respectively) them from the PyJWT object's whitelist.
=> Added support for whitelist validation of the `alg` header

tests/test_algorithms.py
Previously in this test, we were making the signature invalid by adding "123" to the end of the signature bytes. In Linux, this would result in the test passing but in OS X the test would fail.
According to [JWA](https://tools.ietf.org/html/draft-ietf-jose-json-web-algorithms-40#section-3.4) , the ECDSA signature is composed of two 256-bit unsigned ints that are encoded into octets and concatenated to form the 64-byte JWS signature. It looks like the underlying crypto library on Linux ignored the extra values that I was appending to the signature and OS X did not resulting in the test passing on Linux and failing on OS X.
This PR modifies the test to replace a single known byte contained within the 64-bytes of the EC signature. This works in all environments since it is an invalid …
=> Fixed a flaky test for EC validation that would fail on OS X

jwt/api.py, tests/test_api.py
If `iat`, `nbf`, or `exp` are not valid int values, a DecodeError will be raised.
This fixes #121
=> Add checks to int claims (nbf, iat, exp) to verify they are actually ints

tests/test_api.py
One of the biggest advantages to tests is that they allow us to test the public APIs of the library independent of the underlying implementation (private APIs). This allows us to completely change the underlying implementation while having confidence that our library still works.
This PR changes all of our tests that use private APIs and methods and refactors them to focus on public APIs. All of the code is still being tested; its just being tests through only public APIs now.
**NOTE: Please review #122 before this one. (This PR is based off of #122 and will be much less confusing once it is merged)
=> Refactor tests to remove references to private API methods

jwt/__init__.py, jwt/api.py, jwt/exceptions.py, tests/test_api.py
* Added checks on iat to make sure that a token can't be issued for the future
* Changed nbf exception to ImmatureSignatureError (matches ruby-jwt)
=> Add check for iat and new exception for nbf claims

AUTHORS, CHANGELOG.md, README.md, jwt/api.py, tests/test_api.py
This adds the ability to use a more flexible option dictionary.  The options dictionary can be specified at the PyJWT object level or as an override passed directly into `decode()`
Attempts to fix #127
=> Add flexible and complete verification options

CHANGELOG.md, README.md, jwt/algorithms.py, tests/test_algorithms.py, tests/test_api.py
Added support for RSASSA-PSS algorithms (PS256, PS384, PS512)
The JWT spec also mentions optional support for RSASSA-PSS using and MGF1. This is superior to PKCS #1 v1.5 (RS256, RS384, RS512) because it essentially uses a salt to randomize the padding instead of using a completely deterministic algorithm. No good attacks against PKCS #1 v1.5 padding currently exist, but PSS is recommended in new applications since it makes the signature even more random.
More info here: http://www.emc.com/emc-plus/rsa-labs/historical/raising-standard-rsa-signatures-rsa-pss.htm
Also added a test to cover our only uncovered line in `jwt.api`
=> Added support for RSASSA-PSS algorithms (PS256, PS384, PS512)

CHANGELOG.md, jwt/api.py, tests/test_api.py
Added a deprecation warning for using verify= instead of options= on decode()
This is mostly to direct users to use `options=` instead of `verify=False` if they need to disable or skip verification so that we can remove this parameter in the next version.
=> Added a deprecation warning for using verify= instead of options= on decode()

bin/jwt
I tried running the example invocation 
jwt --key=secret iss=me exp=1302049071
This failed and returned an error "Not enough segments" followed by a sys.exit(1).
It looks like it tried to parse the encoding parameters and JWT token data, which obviously fails.
I've worked around it and the example scenario's work,but may be a --encode/--decode parameter would be more explicit.
=> Fixed command line encoding

README.md
Based off the work done in #139, I went ahead and changed anywhere in the README where we showed code followed by expected output to use the docstring convention of preceding the Python code with `>>>`.
I opted to leave the places where we just gave code examples alone (no `>>>`) since this seemed to be a little tidier.
=> Converted some of the README lines from the last PR to use docstring-like conventions

CHANGELOG.md, jwt/api_jwt.py, tests/test_api_jwt.py
Fix for #147
- Merge with `verify_exp` option
- Add deprecation warning
@mark-adams thoughts?
=> `verify_expiration` was removed too soon

jwt/api_jwt.py
Made options a mandatory argument to PyJWT._validate_claims and reordered the arguments to reflect the change. Resolves #148.
=> Made options a mandatory argument to PyJWT._validate_claims

.travis.yml, CHANGELOG.md, jwt/compat.py, setup.py
`cryptography` dropped support for Python 3.2 in v0.9 and I think we should to. Its probably one of the more awkward Python releases and has weird quirks that aren't shared by 3.3+
cc: @jpadilla
=> Remove Python 3.2 support

tests/keys/__init__.py, tests/keys/jwk_ec_key.json, tests/keys/jwk_ec_pub.json, tests/keys/jwk_hmac.json, tests/keys/jwk_rsa_key.json, tests/keys/jwk_rsa_pub.json, tests/test_algorithms.py, tests/utils.py, tox.ini
The [JOSE Cookbook](https://www.ietf.org/id/draft-ietf-jose-cookbook-08.txt) has a very good set of test keys / signatures that we can use to verify our algorithms are functioning properly. Considering the recent discovery of our EC implementation being improper, I wanted to add these known good vectors to our test suite to verify everything is working properly prior to merging of #158.
It should be noted that there is a test in here for RSA-PSS that I'm not 100% I've written properly. I went ahead and left the test with a `@skipIf` decorator so that I can go in and fix it tomorrow once I know more about RSA-PSS.
Once this is merged, the EC test should show up as failing and we can use that test to verify #158 has fixed the issue.
=> Added test vectors from the IETF JOSE Cookbook for HMAC, RSA, and EC.

jwt/algorithms.py, jwt/contrib/algorithms/py_ecdsa.py, jwt/utils.py, tests/contrib/test_algorithms.py, tests/test_algorithms.py, tests/test_api_jws.py, tests/test_api_jwt.py
According to the [JSON Web Algorithms Draft, section 3.4](https://tools.ietf.org/html/draft-ietf-jose-json-web-algorithms-40#section-3.4) the ECDSA signature should be serialized by concatenating the R and S values.
The code was using `ecdsa.util.sigencode_der`, that encodes the signature using the DER serialization format, instead of using `ecdsa.util.sigencode_string`, that does exactly what the draft asks.
=> Fix the ECDSA signature serialization format

CHANGELOG.md, jwt/algorithms.py, tests/test_algorithms.py
When we added the [RFC 7520](https://tools.ietf.org/html/rfc7520) test vectors to our project, the RSA-PSS algorithm test would not pass.
After further review, it turns out that I improperly implemented this originally. JWA [clearly specifies](https://tools.ietf.org/html/draft-ietf-jose-json-web-algorithms-31#section-3.5) how the salt length should be set:
> The size of the salt value is the same size as the hash function output.
This PR corrects that issue and removes some redundant tests from our original test suite for algorithms since the RFC 7520 tests accomplish the same thing.
=> RSA-PSS should use the proper salt value when creating and verifying signatures

CHANGELOG.md, README.md, jwt/__init__.py, jwt/api_jwt.py, jwt/exceptions.py, tests/test_api_jwt.py, tests/test_exceptions.py
Added the require_exp, require_iat, and require_nbf claims so that applications can indicate that they expect these claims to be present. If they are not present. These options are set to false by default.
A new exception type, MissingRequiredClaimError, is introduced. The `claim` property indicates which claim is missing. When `audience=` or `issuer=` is present on `decode()`, MissingRequiredClaimError is now raised instead of the previous exceptions.
Thanks to @dbaxa from @Atlassian for the suggestion.
=> Added new options for requiring exp, iat, and nbf claims.

jwt/api_jws.py, tests/test_api_jws.py
The [JWS spec states that if `kid` is present then it **MUST** be a string](https://tools.ietf.org/html/draft-ietf-jose-json-web-signature-41#section-4.1.4). Currently, the library allows silent creation of invalid JWS (and thus, JWT), as it allows any type for `kid`.
Allowing arbitrary types is both against the spec, and has some potential security ramifications that I've seen crop up. Since header values *can* be used pre-verification (and in the case of `kid`, might be required to verify), some more strictness around them and ensuring they meet the spec makes sense.
=> Fail on encode and decode of bad JWS header values

setup.py, tox.ini
Current versions of Pytest can't detect deprecation warnings.
This was fixed in https://github.com/pytest-dev/pytest/pull/1081 but is not released yet.
=> Fixes an issue where the newer versions of Pytest can't detect deprecation warnings

jwt/api_jws.py, jwt/compat.py, tests/test_api_jws.py
Fixed #183 AttributeError: 'NoneType' object has no attribute 'rsplit'
The issue also occurs when payload is int raising:
AttributeError: 'int' object has no attribute 'rsplit'
Test for None and int payload added
=> Fixed #183 AttributeError: 'NoneType' object has no attribute 'rsplit'

README.md
The example contained incorrect syntax, simply swapped the comma for the existing period.
=> Fixed example usage

jwt/__main__.py
The --no-verify option disables both signature verification and claims verification (e.g. expiry); reflect that in the command-line help.
=> Reflect that --no-verify also ignores claims

tests/test_algorithms.py
Just noticed a couple of @pytest.mark.skipif decorators that were skipping tests if `cryptography` was not installed that were on HMAC tests which have no dependency on `cryptography`
=> Remove some erroenous @pytest.mark.skipif decorators

.travis.yml, appveyor.yml, setup.py, tox.ini
Just noticed we don't have Python 3.5 set up for our CI builds. This adds Python 3.5 and changes some of our single version builds to use 3.5 instead of 3.4.
=> Add Python 3.5 to CI builds

setup.cfg
Apparently a flake8 or tox update caused .tox to be included in the flake8 check. As you can imagine, that turns out badly for everyone involved.
This PR fixes that by excluding .tox from the flake8 check
=> Flake8 now ignores .tox

jwt/algorithms.py, jwt/compat.py, setup.cfg, tests/test_algorithms.py
On Python 3.4, if a private key is passed into `algo.prepare_key()` as a `bytes` object, it will raise a `TypeError`
The following test case demonstrates the issue.
```
def test_rsa_should_accept_pem_private_key_bytes(self):
algo = RSAAlgorithm(RSAAlgorithm.SHA256)
with open(key_path('testkey_rsa'), 'rb') as pem_key:
algo.prepare_key(pem_key.read())
```
cc: @jpadilla
=> Fix a bug where a PEM private key as bytes raises a TypeError

jwt/algorithms.py, jwt/api_jws.py, jwt/compat.py, jwt/utils.py, tests/contrib/test_algorithms.py, tests/keys/__init__.py, tests/test_algorithms.py, tests/test_api_jws.py, tests/test_compat.py, tests/test_utils.py, tests/utils.py
This adds support for JWK serialization to HMAC and RSA keys.
Looking something like this:
```python
public_key = RSAAlgorithm.from_jwk('{"kty": "RSA", "e": "AQAB", ...')
```
and also 
```python
jwk = RSAAlgorithm.to_jwk(public_key)
print(jwk)
> '{"kty": "RSA", "e": "AQAB", ...'
```
```
=> Add JWK support for HMAC and RSA keys

README.md
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
=> Convert readthedocs link for their .org -> .io migration for hosted projects

docs/algorithms.rst, jwt/algorithms.py, tests/test_api_jws.py
Per the [RFC on ECDSA in TLS](https://tools.ietf.org/html/rfc4492#appendix-A), the signing algorithm using the P-521 elliptic curve and SHA-512 is called ES521, instead of ES512.
=> Fix incorrectly named ECDSA algorithm

setup.py
```python3 setup.py bdist_rpm ``` failed because of non asci symbol.
=> Fix rpm build

jwt/algorithms.py
#219 renamed the incorrect `ES512` to `ES521` but we want to keep `ES512` for now in order to maintain backwards compatibility (for now)
=> Add back 'ES512' for backward compatibility (for now)

CHANGELOG.md, jwt/__main__.py, setup.py
So, instead of getting rid of the jwt CLI script as we discussed in #130, what do you think about just renaming it to jwt-cli so that it doesn't overlap with `jwt` anymore? That should pretty much fix any outstanding issues.
Thoughts @jpadilla?
=> Renamed jwt CLI script to jwt-cli to avoid issues with jwt script overlapping with the jwt package.

jwt/utils.py, setup.py
The functions `decode_rfc6979_signature` and `encode_rfc6979_signature`
were deprecated in cryptography 1.0:
https://github.com/pyca/cryptography/blob/master/CHANGELOG.rst#10---2015-08-12
and raise a DeprecationWarning now. The replacements are exactly the same.
=> Require cryptography >= 1.0, replace deprecated functions

CHANGELOG.md, jwt/algorithms.py, jwt/contrib/algorithms/py_ecdsa.py, jwt/contrib/algorithms/pycrypto.py, jwt/exceptions.py, tests/contrib/test_algorithms.py, tests/test_algorithms.py
Our error handling in Algorithm.prepare_key() was previously weird and
kind of inconsistent. This change makes a number of improvements:
* Refactors RSA and ECDSA prepare_key() methods to reduce nesting and
make the code simpler to understand
* All calls to Algorithm.prepare_key() return InvalidKeyError (or a
subclass) or a valid key instance.
* Created a new InvalidAsymmetricKeyError class that is used to provide
a standard message when an invalid RSA or ECDSA key is used.
=> Refactor error handling in Algorithm.prepare_key() methods

CHANGELOG.md, docs/usage.rst, jwt/api_jwt.py, tests/test_api_jwt.py
This change resolves #190 by no longer rejecting future `iat` claims.
RFC 7519 does not require or even mention this type of validation so it seems best to leave this up to applications.
In addition, this PR changes the validation that rejects non-numeric `iat` values to raise `InvalidIssuedAtError` instead of `DecodeError`
=> Remove rejection of future 'iat' claims

setup.cfg, setup.py
Previously, pytest was pinned to an old version because of a bug in
pytest that has since been fixed. This change now puts us back to using
the latest version of pytest.
This fixes #253.
=> Bump pytest version to latest

.travis.yml, setup.py, tox.ini
Enable running tests against python 3.6 in Travis
=> enable testing with python 3.6

jwt/__init__.py
=> Expose InvalidAlgorithmError on jwt module

.coveragerc, .travis.yml, jwt/__main__.py, tests/test_cli.py
- Change optparse for the more modern argparse.
- Refactored main() to fit new argparse code.
- Added two subcommands: encode and decode
- Added default functions for encode and decode subcommands
- Replaced implicit arguments with standard Python syntax in usage text.
=> Change optparse for argparse.

jwt/api_jws.py, jwt/api_jwt.py
I've thought about adding `stacklevel=2`, but it is used internally / passed through, so that might not be that helpful.
=> DeprecationWarnings: more helpful message

jwt/api_jws.py, jwt/api_jwt.py
Followup to https://github.com/jpadilla/pyjwt/pull/270:
It seems that "verify" is only deprecated with `PyJWS.decode`, which
makes sense, since you would have to override a lot of options to skip
the verification in `PyJWT._validate_claims`.
This makes `PyJWT.decode` use the `verify_signature` option when calling
`PyJWT.decode`, and therefore also allows to use `stacklevel=2` there
then for the DeprecationWarning.
=> PyJWT.decode: move verify param into options

docs/index.rst, docs/usage.rst
11f30c4050a11b6398d38f505578c9dabeba6c78 changes things so that a deprecation warning is raised when algorithms isn't specified in the jwt.decode(). This just updates the documentation to match. It also updates the first encode/decode example in the docs so you don't have to scroll a ways to the right in order to see that you need the `secret` and `algorithms` args.
=> Include 'algorithms' kwarg in jwt.decode() (documentation)

CHANGELOG.md, jwt/algorithms.py, setup.py
The signer/verifier interfaces are deprecated in cryptography==2.0. The
alternative sign/verify interfaces were added in cryptography==1.4.
=> Require cryptography >= 1.4, replace deprecated functions

CHANGELOG.md, jwt/api_jws.py, jwt/api_jwt.py, tests/test_api_jws.py, tests/test_api_jwt.py
Since no signature verification will occur, passing in `algorithms` does
not make much sense.
=> Warn about missing algorithms arg only when verify is True

.gitignore, jwt/__main__.py, tests/test_cli.py
=> Fix over-eager fallback to stdin

docs/usage.rst, jwt/api_jws.py, jwt/api_jwt.py, jwt/contrib/algorithms/pycrypto.py, tests/test_api_jws.py, tests/test_api_jwt.py, tests/utils.py
Some users have complained that the docs don't make it very clear that
the private key / public key need to be a byte string. This change makes
that clearer by adding an example to usage.rst.
=> docs: Add example of encoding and decoding tokens with RSA

docs/algorithms.rst
The hyperlink formatting was in Markdown while the document is in reStructuredText. Simply changing the formatting to match. Also making the link https. This is a security-oriented library, after all.
=> Fix hyperlink formatting in algorithms.rst

jwt/__init__.py
=> Expose InvalidSignatureError on jwt module

AUTHORS, CHANGELOG.md, jwt/api_jwt.py, tests/test_api_jwt.py
If the application does not specify an audience, but the token does, then throw an `InvalidAudienceError`.
=> Fix bug if application does not specify audience

docs/installation.rst
Related to #181 where users see `ValueError: Algorithm already has a handler.` after trying to register pycrypto algorithms. You must unregister the original handler first.
=> Update legacy instructions for using pycrypto

jwt/__init__.py, jwt/exceptions.py
I was trying to use pyjwt in some (connexion/flask) apps. I wanted to have all the jwt-related errors be converted into something (a `connexion.exceptions.ProblemException`  subclass) which my app could recognize as an auth failure & thus respond with 401. Maybe some of the exceptions should be treated as 5xx (I haven't actually tried to figure out exactly what they all mean yet), but nevermind.
It's not obvious from the API dox or even the code how to catch all the pyjwt exceptions. So I had what turn out to be the two base classes inherit from `PyJwtError` and made a comment explaining the purpose.
If this was my repo, I'd make the comment say "All exceptions _MUST_ inherit from `PyJwtError`" and reject any pr which adds an exception which doesn't, but it's not so that seems kinda …
=> all exceptions inherit from PyJwtError

docs/usage.rst
=> Added section to usage docs for jwt.get_unverified_header()

CHANGELOG.md, jwt/__init__.py, jwt/api_jws.py, jwt/api_jwt.py
@jpadilla Can you give a quick review to this so we can get a new release out to fix this breaking API change?
=> Fix #351 by reverting argument name changes for .decode()

.travis.yml
- remove workaround for running tests with python 3.5
- switch to using travis build matrix for testing different python versions, docs [here](https://docs.travis-ci.com/user/customizing-the-build#Build-Matrix)
In [this PR](https://github.com/jpadilla/pyjwt/pull/262) a workaround was added in order to enable CI testing with python 3.6 due to python3.5 not being available in the test environment by default. See comments on the PR for details.
The workaround is no longer needed and can be removed. This code change is intended as cleanup and to facilitate testing with Python 3.7 which is going to be released shortly.
=> travis cleanup

README.rst, docs/index.rst
The example invocations for decoding JWT tokens in the README appear to be incorrect. This PR, if applied, will fix the same.
=> Fixes example invocations in README.rst and index/docs.rst.

jwt/api_jwt.py
As discussed [here](https://github.com/jpadilla/pyjwt/issues/392) the return type for `decode` should be `dict[str, Any]` instead of the (inferred) `Mapping[any, any]`, this adds it.
Mapping is an ABC and I think the check with `isinstance` maybe was more appropriate, but still we know it is going to be a dictionary in any case so should be fine.
=> Decode return type is dict[str, Any]

tests/test_cli.py
This fixes the failure that's causing CI tests to fail.
=> Fix linter error in test_cli

tox.ini
Avoids use of easy_install and interaction between flake8 and tests. Fixes #416.
=> Invoke pytest directly.

jwt/api_jws.py, jwt/api_jwt.py
Per recent upstream fix to typeshed, json.dumps() cls argument should be
optional type JSONEncoder.
https://github.com/python/typeshed/commit/8e0d288ea49a34f9bd21b1598ec487414a339a1f
Fixes mypy error:
jwt/api_jws.py:102: error: Argument "cls" to "dumps" has incompatible type "Optional[Callable[..., Any]]"; expected "Optional[Type[JSONEncoder]]"
jwt/api_jwt.py:61: error: Argument "cls" to "dumps" has incompatible type "Optional[Callable[..., Any]]"; expected "Optional[Type[JSONEncoder]]"
=> Correct type for json_encoder argument

setup.cfg, setup.py
Using pytest and tox directly is simpler and more conventional then
going through setup.py. Using setup.py installs packages as eggs where
as tox uses the more typical pip.
Overall simplifies setup.py.
Fixes #415
=> Remove setup.py test command in favor of pytest and tox

jwt/help.py
```
mypy create: /home/travis/build/jpadilla/pyjwt/.tox/mypy
mypy inst: /home/travis/build/jpadilla/pyjwt/.tox/.tmp/package/1/PyJWT-1.7.1.zip
mypy installed: mypy==0.740,mypy-extensions==0.4.3,PyJWT==1.7.1,typed-ast==1.4.0,typing-extensions==3.7.4
mypy run-test-pre: PYTHONHASHSEED='2425519668'
mypy run-test: commands[0] | mypy --ignore-missing-imports jwt
jwt/help.py:12: error: Incompatible types in assignment (expression has type "None", variable has type Module)
Found 1 error in 1 file (checked 13 source files)
ERROR: InvocationError for command /home/travis/build/jpadilla/pyjwt/.tox/mypy/bin/mypy --ignore-missing-imports jwt (exited with code 1)
```
=> Fix mypy errors

jwt/contrib/algorithms/py_ecdsa.py
The new ecdsa no longer uses AssertionError when the signature is too long.
This happens in the test suite, where "123" is appended to the signature.
Fixes #447
=> Catch BadSignatureError raised by ecdsa 0.13.3 on verification errors

.travis.yml, setup.py, tox.ini
Python 3.8 is out, let's make pyjwt CI and package compatible
=> Add support of python 3.8

setup.py
`!=3.0.*, …` was only necessary to support both `2.7` and `>=3.x`
=> Simplify `python_requires`

docs/usage.rst
Hello `pyjwt` maintainers,
I've recently been using the `pyjwt` codebase to decode JWT tokens originating from [Keycloak](https://www.keycloak.org/) servers, where the JWT `aud` claim is an array by default, and I'm dealing with a `python` `API` server that supports multiple `audiences`.
The edits I've made in this PR hope to improve the documentation for users who are not as familiar with the specific details surrounding the `audience` claim, like I was until I started digging into using `pyjwt` more.
Makes an explicit code block example for the `aud` claim being an `array`. It was mentioned in the text, but I think making a code block demonstrating it helps make it more clear.
Adds an example of the `audience` param for `jwt.decode` supporting an iterable argument, as implemented in …
=> Improve documentation for audience usage

docs/api.rst, docs/usage.rst
Document `jwt.encode` and `jwt.decode` and close #459 (maybe, I mean, the classes need to be documented too, but maybe that's not as important).
Also clean up rst heading markup because shpinx complained about that.
=> Document top-level .encode and .decode to close #459

docs/usage.rst, jwt/api_jwt.py, tests/test_api_jwt.py
Goes ahead with the proposal in https://github.com/jpadilla/pyjwt/issues/279
Added a test and documentation on how to use the new parameter.
I took the liberty to deprecate the 'verify_xxx' options while still allowing them (as evidenced by the existing tests)
Feel free to critique any of the changes.
=> Require tweak

jwt/api_jws.py
Seen a traceback like this:
```
$ python3 -c 'import jwt; jwt.decode("foo")'
/home/mdk/clones/pyjwt/jwt/api_jwt.py:88: DeprecationWarning: It is strongly recommended that you pass in a value for the "algorithms" argument when calling decode(). This argument will be mandatory in a future version.
warnings.warn(
Traceback (most recent call last):
File "/home/mdk/clones/pyjwt/jwt/api_jws.py", line 189, in _load
signing_input, crypto_segment = jwt.rsplit(b".", 1)
ValueError: not enough values to unpack (expected 2, got 1)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/home/mdk/clones/pyjwt/jwt/api_jwt.py", line 95, in decode
payload, _, _, _ = self._load(jwt)
File …
```
=> Enhance tracebacks.

README.rst
The command `setup.py test` has been unused since
3a20892442b34c754b26550e05f7f856fb008c94.
=> Correct README on how to run tests locally

setup.py
Documents the project as Python 3 only to potential and current library
users.
As the project no longer supports Python 2, the wheel is not
"universal". From
https://wheel.readthedocs.io/en/stable/user_guide.html?highlight=universal#building-wheels:
> If your project … is expected to work on both Python 2 and 3, you will
> want to tell wheel to produce universal wheels …
=> Add Python-3-only trove classifier and remove "universal" from wheel

docs/conf.py, jwt/__init__.py, jwt/__main__.py, jwt/algorithms.py, jwt/api_jws.py, jwt/api_jwt.py, jwt/help.py, tests/contrib/test_algorithms.py, tests/keys/__init__.py, tests/test_algorithms.py, tests/test_api_jws.py, tests/test_api_jwt.py, tests/test_cli.py
pyupgrade is a tool to automatically upgrade Python syntax for newer
versions of the language. Running pyupgrade removes several
Python-2-isms that are no longer necessary now that the project is
Python 3 only.
https://github.com/asottile/pyupgrade
=> Run pyupgrade across project to use modern Python 3 conventions

jwt/api_jws.py, jwt/api_jwt.py
This assumes all direct calls to private methods (leading underscore in name) are from pyjwt code, hence stacklevel=3 nor 2.
=> Emit warnings about user code, not pyjwt code

jwt/__main__.py
Currently the pyjwt command can't verify a token that has an 'aud' included. Added the --audience option to specify an acceptable audience, and allow it multiple times.
While I'm at it, added --issuer option as well.
=> CLI options for verifying audience and issuer

jwt/__init__.py
This allows one to import that error similar to other errors:
```
from jwt import InvalidKeyError
```
=> Expose InvalidKeyError on jwt module

README.rst
Proposed change to address #507 
The default readthedocs links point to the latest documentation based on the master branch. The latest documentation is not consistent with the stable release of PyJWT 1.7.1. The "About" section of the repository also links to the latest documentation.
=> Default links to stable version of documentation

README.rst, docs/index.rst, jwt/api_jws.py
=> Return tokens as string not bytes

jwt/__init__.py, jwt/algorithms.py, jwt/api_jwk.py, jwt/api_jws.py, jwt/api_jwt.py, jwt/exceptions.py, jwt/jwks_client.py, pyproject.toml, setup.cfg, tests/test_api_jwk.py, tests/test_jwks_client.py
Extracted from #470
Introduce `PyJWK`, `PyJWKSet`, and `PyJWKClient`.
```python
import jwt
from jwt import PyJWKClient
token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik5FRTFRVVJCT1RNNE16STVSa0ZETlRZeE9UVTFNRGcyT0Rnd1EwVXpNVGsxUWpZeVJrUkZRdyJ9.eyJpc3MiOiJodHRwczovL2Rldi04N2V2eDlydS5hdXRoMC5jb20vIiwic3ViIjoiYVc0Q2NhNzl4UmVMV1V6MGFFMkg2a0QwTzNjWEJWdENAY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vZXhwZW5zZXMtYXBpIiwiaWF0IjoxNTcyMDA2OTU0LCJleHAiOjE1NzIwMDY5NjQsImF6cCI6ImFXNENjYTc5eFJlTFdVejBhRTJINmtEME8zY1hCVnRDIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.PUxE7xn52aTCohGiWoSdMBZGiYAHwE5FYie0Y1qUT68IHSTXwXVd6hn02HTah6epvHHVKA2FqcFZ4GGv5VTHEvYpeggiiZMgbxFrmTEY0csL6VNkX1eaJGcuehwQCRBKRLL3zKmA5IKGy5GeUnIbpPHLHDxr-GXvgFzsdsyWlVQvPX2xjeaQ217r2PtxDeqjlf66UYl6oY6AqNS8DH3iryCvIfCcybRZkc_hdy-6ZMoKT6Piijvk_aXdm7-QQqK …
```
=> Introduce better experience for JWKs

.github/workflows/main.yml, setup.cfg, tox.ini
The Python 3.9 jobs on windows currently fails with
> ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly
cryptography provides abi3 wheels, but they are only available for cryptography>=3 on windows.  Wheels for Python 3 probably won't be available for cryptography < 3.  ~Is removing the upper bound worth investigating?~
**Update:**
I've checked the [changelog](https://github.com/pyca/cryptography/blob/master/CHANGELOG.rst) and gave it a try.  All the tests pass with cryptography 3.x.
=> Run tests against Python 3.9 and add trove classifier

docs/faq.rst, jwt/algorithms.py, tests/keys/__init__.py, tests/test_api_jws.py
- Cryptography now has default_backend by default
Since Cryptography v3.1, backend arguments to functions are no longer required and the default backend will automatically be selected if no backend is provided.
=> Removed redundant `default_backend()`

docs/api.rst
It seems to me that the return type for the encode method is actually 'bytes' type and not 'str'. While this doesn't make a huge difference working with python code, it gave me some issues yesterday when sending JWT tokens between a Python (flask) REST API and Javascript (Vue) frontend.
=> Update return type for jwt.encode

docs/usage.rst
This can address https://github.com/jpadilla/pyjwt/issues/286
=> Documents how to use private keys with passphrases

docs/algorithms.rst
Since the implementation is merged. https://github.com/jpadilla/pyjwt/pull/455 docs too should update. So, none need to search PRs, Issues, Source Code
=> add EdDSA to docs

setup.cfg
Python 3.5 went end-of-life 2020-09-30. See:
https://devguide.python.org/devcycle/#end-of-life-branches
=> Remove support for EOL Python 3.5

jwt/api_jwt.py
Removes a duplicate call to `_load` in `pyjwt.decode` method that is unused.
=> Avoid loading token twice in pyjwt.decode

.pre-commit-config.yaml, jwt/algorithms.py, pyproject.toml, tests/keys/__init__.py, tests/test_algorithms.py
With isort 5, asottile/seed-isort-config is deprecated and unnecessary.
The official isort main repo now has a pre-commit hook file.
isort is now better at recognizing first party and third party packages.
isort can now handle imports inside blocks, files have been updated.
isort now supports "profiles" for simpler configuration.
=> Upgrade to isort 5 and adjust configurations

jwt/api_jws.py
The method signature of PyJWT.decode() now matches the parent
PyJWS.decode().
=> Remove unused argument "verify" from PyJWS.decode()

tox.ini
Fixes the warning when running tests:
.tox/.../lib/python3.9/site-packages/_pytest/config/__init__.py:1233
.../pyjwt/.tox/.../lib/python3.9/site-packages/_pytest/config/__init__.py:1233: PytestConfigWarning: Unknown config option: strict
self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")
=> Drop unknown pytest config option: strict

jwt/api_jws.py, jwt/api_jwt.py, jwt/help.py, setup.cfg, tox.ini
Now that Python 2 is not supported, can move away from type comments to
type annotation 🎉.
The typing module is always available, so remove the guards.
Specify the supported Python in the mypy configuration.
Move other mypy configurations to one place. This way, whether tox is
used or not, the same mypy errors appear.
Distribute and install PEP-561 compliant py.typed file. When PyJWT is a
imported as a library, this tells mypy to use the provided type
annotations rather than going through typeshed. This way, the types are
always up to date when running mypy.
Remove outdated ignores since dropping Python 2.
=> Update typing syntax and usage for Python 3.6+

jwt/algorithms.py, jwt/api_jws.py, jwt/jwks_client.py, tests/keys/__init__.py, tests/test_algorithms.py, tests/test_api_jwk.py, tests/test_api_jws.py, tests/test_api_jwt.py
pyugrade is a command line tool to automatically update Python syntax to
modern usage and patterns. For additional details, see:
https://github.com/asottile/pyupgrade
Changes made by the tool:
- Use short Python3 super() syntax.
- Use f-strings when they are simple and more readable.
- Drop Python 2 u prefix from strings.
- Drop "r" argument from open(). It is the default and so specifying it is
unnecessary.
=> Run pyupgrade to simplify code and use Python 3.6 syntax

README.rst, docs/index.rst
The CLI entry point was removed in commit
8a14f087c285bbe2f6e85ba4818e6c620b708d5d.
=> Remove "Command line" sections from docs

jwt/algorithms.py, tests/keys/__init__.py
The first line of base64url_decode() is:
if isinstance(input, str):
input = input.encode("ascii")
It therefore accepts either str or bytes. Don't bother coercing to bytes
at the call site.
=> Remove unnecessary force_bytes() calls priot to base64url_decode()

jwt/api_jws.py, jwt/api_jwt.py, tests/test_api_jws.py
Since Python 3.6, json.loads() accepts both Unicode and byte strings.
https://docs.python.org/3/library/json.html#json.loads
> Changed in version 3.6: s can now be of type bytes or bytearray. The
> input encoding should be UTF-8, UTF-16 or UTF-32.
=> Remove unnecessary Unicode decoding before json.loads()

docs/api.rst, docs/usage.rst
They were removed from the code in
f690976596bb74221f5a81fc9afffd5609bc4e70.
=> Remove deprecated arguments from docs

jwt/jwks_client.py, setup.cfg, tests/test_jwks_client.py
Allows dropping a dependency that isn't very necessary.
The requests library was used for a single line of code. This same code
is just as easily expressible using the stdlib, thus alllows removing a
dependency.
Tests were adjusted to mock this new approach.
=> Refactor jwt/jwks_client.py without requests dependency

tests/test_algorithms.py, tests/test_api_jws.py
Now that Python 2 has been dropped, can safely use bytes
literals (b"abc") and string literals.
=> Replace force_bytes()/force_unicode() in tests with literals

jwt/api_jws.py, jwt/api_jwt.py
=> Enforce .encode() return type using mypy

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/Bug.md, .pre-commit-config.yaml, README.rst, docs/algorithms.rst, docs/faq.rst, docs/index.rst, docs/usage.rst
Update Python 2 syntax and drop Python-2-only examples.
Fix all Python console prompts to the full ">>> " for correct
highlighting.
Use "pycon" instead of "python" for interactive Python console session.
The "python" lexer is for Python scripts and doesn't interpret the ">>>"
prompt.
Fix all Python console code blocks to more accurately display what the
user will see. For example, when assigning a value to a variable, it
isn't also echoed.
Fix typo ".. code::" → ".. code-block::".
Use "console" instead of "sh" for shell sessions. The "sh" lexer is for
shell scripts. For a complete list of lexers, see:
https://pygments.org/docs/lexers/
Use blacken-docs to run black on code blocks.
=> Update code blocks in docs

jwt/algorithms.py, jwt/api_jws.py, jwt/utils.py, tests/test_api_jws.py, tests/test_utils.py, tox.ini
Now that the project is Python 3 only, the boundaries between bytes and
Unicode strings is more explicit.
This allows removing several unnecessary force_bytes() and
force_unicode() calls that handled differences between Python 2 and
Python 3. All uses of force_unicode() have been removed.
For values that are known to be bytes, use `.decode()` instead. For
values are that known to be str, use `.encode()` instead. This strategy
makes the type explicit and reduces a function call.
Key handling continues to use force_bytes() to allow callers to pass
either bytes or str.
To help enforce bytes/str handling in the future, the `-b` option is
passed to Python when testing. This option will emit a warning if bytes
and str are improperly mixed together.
=> Tighten bytes/str boundaries and remove unnecessary coercing

docs/conf.py
Since Python 3, these two functions are functionally equivalent, so use
the builtin one.
=> Replace codecs.open() with builtin open()

jwt/algorithms.py, tests/keys/__init__.py, tests/utils.py
Follows upstream cryptography commit:
https://github.com/pyca/cryptography/commit/5528a3182fdd6ed1c44c126d451a87bcf39e79de
Since Python 3.2, this bytes to an int is a native feature.
=> Replace int_from_bytes() with builtin int.from_bytes()

jwt/api_jwt.py
Default options are set using PyJWT._get_default_options() therefore,
there should never be a KeyError when indexing options directly. Enforce
this expectation. Also avoids duplicating the default for the "require"
option.
=> Prefer direct indexing over options.get()

jwt/api_jws.py, jwt/api_jwt.py, jwt/utils.py
Merging two dict is support since Python 3.5 using the ** syntax.
See:
- https://docs.python.org/3.9/whatsnew/3.5.html#whatsnew-pep-448
- https://www.python.org/dev/peps/pep-0448/
=> Replace merge_dict() with builtin dict unpacking generalizations

jwt/jwks_client.py
When complete=True is passed to api_jwt.decode() (aliased as
decode_token()), the "header" key always exists.
=> Use direct indexing in PyJWKClient.get_signing_key_from_jwt()

jwt/__init__.py, jwt/api_jws.py, jwt/api_jwt.py, jwt/jwks_client.py, jwt/utils.py, tests/test_api_jws.py, tests/test_api_jwt.py
The class PyJWT was previously a subclass of PyJWS. However, this
combination does not follow the Liskov substitution principle. That is,
using PyJWT in place of a PyJWS would not produce correct results or
follow type contracts.
While these classes look to share a common interface it doesn't go
beyond the method names "encode" and "decode" and so is merely
superficial.
The classes have been split into two. PyJWT now uses composition instead
of inheritance to achieve the desired behavior. Splitting the classes in
this way allowed for precising the type interfaces.
The complete parameter to .decode() has been removed. This argument was
used to alter the return type of .decode(). Now, there are two different
methods with more explicit return types and values. The new method name
is …
=> Split PyJWT/PyJWS classes to tighten type interfaces

jwt/utils.py
int.from_bytes() has been available since Python 3.2. Using it avoids
string formatting.
=> Simplify from_base64url_uint()

jwt/algorithms.py, jwt/help.py, jwt/utils.py, tests/keys/__init__.py, tests/test_algorithms.py, tests/test_api_jwk.py, tests/test_api_jws.py
ModuleNotFoundError was introduced in Python 3. It is raised when the
module does not exist. On the other hand, ImportError is raised during
any import failure. For example, a syntax error or other runtime error.
Using ModuleNotFoundError means that errors unrelated to a missing
package will be propagated to the user. PyJWT doesn't know how to handle
these.
This also allows more functions to always be available for import
=> Prefer ModuleNotFoundError over ImportError

.flake8, .pre-commit-config.yaml, MANIFEST.in, setup.cfg, tox.ini
The command `tox -e manifest` now passes.
Added missing files to the sdist:
- .pre-commit-config.yaml
- CODE_OF_CONDUCT.md
- jwt/py.typed
- docs/
Alphabetized MANIFEST.in
Moved .flake8 to setup.cfg to avoid the need to include yet another file
to MANIFEST.in.
Exclude codecov.yml. This is for CI only.
=> Fix tox "manifest" environment to pass

README.rst, docs/api.rst, docs/conf.py, docs/index.rst
- Fixed doctest which included incorrect output.
- Use intersphinx to allow linking to Python JSONEncoder class.
- Fix param types after previous str/bytes cleanups.
- Fix param syntax to avoid vertical bar.
The command `tox -e docs` now passes.
=> Fix tox "docs" environment to pass

docs/conf.py, jwt/algorithms.py, jwt/api_jwk.py, jwt/api_jws.py, jwt/api_jwt.py, jwt/jwks_client.py, pyproject.toml, setup.cfg, tests/test_algorithms.py, tests/test_api_jws.py, tests/test_api_jwt.py, tests/test_jwks_client.py, tests/utils.py
Avoid extra configuration by simply going with Black defaults. This
allows removing some configuration options, thus simplifying the overall
configuration.
It also makes the code style closer to community conventions. As more
projects adopt black formatting, more code will look like the black
defaults.
Further, the default 88 tends to create more readable lines, IMO. The
black rationale is located at:
https://black.readthedocs.io/en/stable/the_black_code_style.html#line-length
=> Simplify black configuration to be closer to upstream defaults

tox.ini
The lint stage of CI is already handled by pre-commit.ci. With it, the
extra run in GitHub action is redundant and only consumes time and
resources unnecessarily.
pre-commit.ci is also faster to respond with results.
=> Drop lint environment from GitHub actions in favor of pre-commit.ci

jwt/algorithms.py
Avoids building a list in memory unnecessarily. Generator expressions
are evaluated lazily.
=> Use generator expressions

.github/workflows/main.yml, tox.ini
Remove the extra dimension: {windows,linux}. In local testing, this
suffix has no practical effect on test runs as the OS is always either
Linux or Window. Adding this suffixes forces many extra test runs when
simply using the command "tox". This has been removed to avoid these
extra runs. This allowed removing the environment variable PLATFORM.
Both Windows and Linux still run in CI.
Use only the component "crypto" to install the extra cryptography
package. This simplifies adding Python versions in the future as
modifying this line is no longer required.
Merge suffixes to one line: py{36,37,38,39}-{crypto,nocrypto}. Again,
this simplifies adding Python versions in the future as one needs to
modify only one line.
=> Simplify tox configuration

CHANGELOG.md
Improve documentation in order to close https://github.com/jpadilla/pyjwt/issues/585.
=> Documentation improvement: tell users to use v1.7.1 for py3.5

CHANGELOG.rst, jwt/algorithms.py
This was previously fixed for `RSAAlgorithm`. Closes #593
=> Fix `from_jwk()` for all algorithms

CHANGELOG.rst, jwt/api_jwt.py, tests/test_api_jwt.py
=> Validate claims if configured and verify_signature is not.

CHANGELOG.rst, jwt/jwks_client.py, tests/test_jwks_client.py
The function `get_signing_key` indirectly makes a network call to get the public key. For a project that authenticates requests extremely often, this introduces a *lot* of delay. 
Cache the result of `get_signing_key` so that it gets reused if called with ~~the same client and~~ the same `kid`. 
This should *not* break any projects that are following JWT standards, as while the RFC is [not entirely explicit](https://tools.ietf.org/html/rfc7515#section-4.1.4), common practice dictates that [the `kid` must be unique](https://auth0.com/blog/navigating-rs256-and-jwks/):
> kid: is the unique identifier for the key
Therefore, unless there is somehow a new key added and an old key removed which both somehow have the same `kid` (which I think is a fair assumption), this is not a breaking change. …
=> Cache signing keys

CHANGELOG.rst, jwt/algorithms.py, tests/keys/jwk_ec_key_secp256k1.json, tests/keys/jwk_ec_pub_secp256k1.json, tests/test_algorithms.py, tests/test_api_jws.py
=> Support ES256K.

CHANGELOG.rst, jwt/__init__.py
All other error classes are already here, so I'm assuming this was an oversight.
=> Add missing exceptions.InvalidKeyError to jwt module __init__ imports.

docs/usage.rst
these changes clarify the usage of claims within the usage documentation
=> changed 'paramenter' to 'parameter'

docs/algorithms.rst, docs/api.rst
This seems to be a common temptation (python-social-auth/social-core#514, https://github.com/twilio/twilio-python/pull/560#discussion_r614487375), so we should clarify why it’s a bad idea.
=> Clearly warn against computing algorithms from the token’s alg

docs/api.rst
- Fix incorrect default values in the documentation. (https://github.com/jpadilla/pyjwt/commit/0b537a402c4f0683cab532754a2cdd7fe6d612b0): `verify_aud`, `verify_iat`, `verify_exp`, and `verify_iss` is `True` by default
https://github.com/jpadilla/pyjwt/blob/3993ce1d3503b58cf74699a89ba9e5c18ef9b556/jwt/api_jwt.py#L26-L35
https://github.com/jpadilla/pyjwt/blob/3993ce1d3503b58cf74699a89ba9e5c18ef9b556/jwt/api_jwt.py#L98-L100
- Add missing option `verify_nbf` to documentation (https://github.com/jpadilla/pyjwt/commit/e92ef3df069c0287c957d077d9869b3af4b03be8)
https://github.com/jpadilla/pyjwt/blob/3993ce1d3503b58cf74699a89ba9e5c18ef9b556/jwt/api_jwt.py#L132-L133
- Set `require` to be  list (https://github.com/jpadilla/pyjwt/commit/692adae4cce44526d5b01ee7bd95b22b7e61f741) …
=> Fix incorrect documentation for jwt

docs/api.rst
- Added documentation for `jwt.decode_complete`.
I'm honestly unsure if everything needs to be duplicated or not since the only thing that is different to `jwt.decode` is the return value. I'm happy to just write `Parameters: Sames as jwt.decode` if that is preferred.
- I previously wrote (e.g.) `verify_aud=True`` but will be ignored if ``verify_signature`` is ``False``.` for all the options parameters except `require` and `verify_signature`, but that is a bad way of describing it. 
What I wanted to write was that the value is `True` by default, but will default to `False` if `verify_signature` is set to false. In other words, they default to the same value as `verify_signature`. I, therefore, think that a better way of writing this is `verify_aud=verify_signature`, and then move …
=> Complete `jwt` documentation

.gitignore
During test runs, new coverage files are generated, such as `.coverage.hostname.number.number`. They get deleted at the end of `tox`, but in the interest of not accidentally committing them during a `tox` run, they should be ignored.
=> Ignore coverage files generated during test runs

CHANGELOG.rst, jwt/api_jwt.py, tests/test_api_jwt.py
Hi, @jpadilla. 
I found a case where a JWT has {"aud": null} header. In the current implementation, if {”aud”: null｝is specified, the audience parameter must be specified on decode() function.
I think {"aud": null} should be treated as the same as that is not specified.
See #669 for details.
Closes #669
=> Fix aud validation to support {'aud': null} case.

CHANGELOG.rst, docs/api.rst, jwt/api_jws.py, jwt/api_jwt.py, tests/test_api_jws.py
Fix #659.
There is an alternate solution that returns error if both `headers[’alg’]` and `algorithm` are set and they are different, I adopted the way to prefer `headers['alg']` to `algorithm` if `alg` is in `headers`.
It can support the following case mentioned in #659 and all of existing tests passed.
```python
key = ...
header = {"typ": "JWT", "alg": "PS256", "kid": "my-key-id"}
claims = {"foo": "bar"}
jws = jwt.encode(payload=claims, key=key, headers=header)
```
Close #659
=> Prefer headers['alg'] to algorithm parameter in encode().

docs/installation.rst, docs/usage.rst
Followup to #208
I faced a similar issue because I read the installation part a little too fast, but I believe this should be clarified over the example many other developers will refer to.
Thanks for this project ❤️
=> DOC: Clarify RSA encoding and decoding depend on the cryptography package

CHANGELOG.rst, jwt/api_jws.py, jwt/api_jwt.py, tests/test_api_jwt.py
Removed arbitrary keyword parameters (**kwargs) that are not being used in order to comply with the current API specification.
As mentioned in #606, I think it's a bit problematic not to get an error if you specify an unsupported argument.
If you agree with this change, I will update a CHANGELOG.
Close #606.
=> Remove arbitrary kwargs.

CHANGELOG.rst, jwt/jwks_client.py, tests/test_jwks_client.py
There's an issue https://github.com/jpadilla/pyjwt/issues/626 about this problem. I ran into it today too.
Currently, when getting signing keys, PyJWKClient assumes that a key is intended for signing, only if its "use" claim is set to "sig". This is not entirely correct, as this claim is optional. If it's omitted, then the key can be used both for signing and encryption. 
I guess the correct way to process fetched keys is to check that their "use" claim is either "sig" or missing. In this case, we can safely append it to the list of signing keys.
=> Assume JWK is valid for signing if "use" is omitted

setup.cfg
Cryptography has adopted a firefox-style versioning system where new
feature releases always have new major versions even if they don't have
backwards incompatible changes. This means that an upper bound on the
dependency does not make sense.
Resolves #692
=> Remove upper bound on cryptography version

CHANGELOG.rst, docs/algorithms.rst, jwt/algorithms.py, tests/keys/jwk_okp_key_Ed448.json, tests/keys/jwk_okp_pub_Ed448.json, tests/test_algorithms.py, tests/test_api_jwk.py
Hi, @jpadilla.
I've added support for Ed448/EdDSA. In order to implement the curve Ed448, I renamed the `Ed25519Algorithm` class to `OKPAlgorithm`. I think it is better because it is more in line with `ECAlgorithm`.
=> Add support for Ed448/EdDSA.

jwt/algorithms.py, jwt/api_jws.py, jwt/api_jwt.py, jwt/jwks_client.py, jwt/utils.py
- I just fix some issues related to code.
- Refactor some Parts of the code.
=> Chore: inline Variables that immediately Returned

docs/usage.rst, jwt/api_jwt.py, tests/test_api_jwt.py, tests/utils.py
This method is deprecated:
https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow
Replaced with:
https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow
using:
https://docs.python.org/3/library/datetime.html#datetime.timezone.utc
which seems to indicate this was added in Python 3.2
=> Use timezone package as Python 3.5+ is required

docs/api.rst
=> documentation fix: show correct scope for decode_complete()

jwt/algorithms.py, tests/test_algorithms.py
Hi!
I was try to encode and sign jwt with ES256 algorithm and key was generated not by me.
And I don't know what kind of key was.
And I fall to same situation as #706  - `TypeError: sign() missing 1 required positional argument: 'algorithm'`
When I dig in  (one hour later)  And it was not incompatible pjwt with cryptography.
The key was RSA (without curve) 
This PR - throws the explicit exception to check your key.
P.S. Sorry for my poor English and feel free to close this PR without merging it
=> Explicit check the key for ECAlgorithm

CHANGELOG.rst, jwt/api_jwk.py, tests/test_api_jwk.py
Adds the API mentioned in #724, as well as a unit test for both happy and error path behavior.
Closes #724.
=> api_jwk: Add PyJWKSet.__getitem__

docs/usage.rst
=> Docs: mention performance reasons for reusing RSAPrivateKey when encoding

docs/usage.rst
In the example [above](https://github.com/jpadilla/pyjwt/edit/master/docs/usage.rst#encoding--decoding-tokens-with-hs256), when tried, it throws a TypeError that says: `encode() got an unexpected keyword argument 'algorithms'`, so I changed the `algorithms` to `algorithm`
=> Fixed typo in usage.rst

jwt/api_jws.py, tests/test_api_jws.py
Specifications allow to have JWS with unencoded detached payloads.
This changeset adds detached payload support for encoding and decoding
functions.
For encoding, detached payload can be enabled by setting the
"is_payload_detached" arg or having the "b64=False" inside the headers.
For decoding, the detached payload content (bytes) has to be provided
with the "detached_payload" arg and "b64=False" has to be found inside
the decoded headers.
Functionnally, when this feature is used, the signature will be computed
over the raw data bytes of the payload, without being base64 encoded and
obviously, the payload will not be provided inside the generated JWS.
So, the generated JWS will look like:
base64url(header)..base64url(signature)
Relevant specifications:
RFC 7515: "JSON Web Signature …
=> Add detached payload support for JWS encoding and decoding

jwt/api_jwt.py, tests/test_api_jwt.py
Since the arbitrary/unused `**kwargs` can't quite be dropped (as #657 would do) without a major version bump (as reverted in #701), it's still a good idea to warn users if they are attempting to use contradictory arguments for the security-sensitive `verify=` argument.
Refs #515 (which dropped `verify=` for 2.x in the first place)
Refs #657 (which dropped the `**kwargs`) 
Refs #701 (which reverted the above)
=> Raise DeprecationWarning for jwt.decode(verify=...)

jwt/api_jwt.py, tests/test_api_jwt.py
`decode_complete()` can do various setdefaults on the passed-in options dictionary, which could be an issue if the options is shared between separate calls. This PR changes the behavior to have `.decode_complete()` operate on a shallow copy of the options instead.
Fixes #679
=> Don't mutate options dictionary in .decode_complete()

jwt/__init__.py, jwt/api_jwk.py, jwt/api_jws.py, jwt/api_jwt.py, jwt/exceptions.py, jwt/help.py, tests/test_algorithms.py
Just a bit of housekeeping. Follows up on #536.
=> Replace various string interpolations with f-strings

.github/workflows/main.yml, tests/test_api_jws.py, tox.ini
PyPy3 raises ValueError rather than TypeError when trying to combine
a dict and a str in dict unpacking.  Update the test expectations
appropriately.
Fixes #580
-----
I've also fixed CI testing for Python 3.10 (no tox targets were run) and added 3.11 and all PyPy3 versions. They seem to all pass on my fork, except for codecov uploads (obviously).
=> Adjust expected exceptions in option merging tests for PyPy3

jwt/algorithms.py
There is a small typo in jwt/algorithms.py.
Should read `isinstance` rather than `iinstance`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, iinstance -> isinstance

CHANGELOG.rst, jwt/__init__.py, jwt/api_jws.py
Looking up an algorithm by name is used internally for signature generation. This encapsulates that functionality in a dedicated method and adds it to the public API. No new tests are needed to exercise the functionality.
Rationale:
1. Inside of PyJWS, this improves the code. The KeyError handler is better scoped and the signing code reads more directly.
2. This is part of the path to supporting OIDC at_hash validation as a use-case (see: #295, #296, #314).
This is arguably sufficient to consider that use-case supported and close it. I believe there is more to do before closing that -- I would like to see Algorithm objects support a method for computing hash digests. However, it is an improvement and step in the right direction in either case.
A minor change was needed to satisfy mypy, as …
=> Expose get_algorithm_by_name as new method

.github/workflows/main.yml, .pre-commit-config.yaml, CHANGELOG.rst, setup.cfg, tox.ini
closes #764 
---
The presence of `py36` in `tox.ini` makes it that much slower to run full tests locally with a bare `tox` invocation. It looks like 3.6 isn't supported anymore, and there's an unfinished PR to remove it. Just take the requisite steps to finish the job.
=> Remove support for python3.6

CHANGELOG.rst, jwt/api_jws.py, jwt/api_jwt.py, jwt/warnings.py, tests/test_api_jws.py, tests/test_api_jwt.py
This is half of #258. It cannot be completed without a breaking release, but the API should be reconsidered at that time because it doesn't make a ton of sense for validation-specific arguments like `leeway` to be presented as args to `decode()`.
---
`**kwargs` usages cannot be removed without breaking backwards compatibility. Unsupported kwargs cannot even be rejected without breaking compatibility.
However, this does not mean that the library cannot identify and warn when unsupported arguments are used. The warning behavior simply has to be separated from any removal of `**kwargs`.
All legitimate `**kwargs` usages have been replaced with explicit arguments. Any other arguments will be captured under `**kwargs` and trigger the deprecation warnings. In the cases of `decode() -> …
=> Emit a deprecation warning for unsupported kwargs

docs/api.rst, jwt/api_jwt.py, tests/test_api_jwt.py
Hello :wave: 
Using the library, I just noticed that the typing of `audience` was not that clear.
There is a difference between:
- [annotations](https://github.com/jpadilla/pyjwt/blob/master/jwt/api_jwt.py#L153)
- [type checking](https://github.com/jpadilla/pyjwt/blob/master/jwt/api_jwt.py#L183)
- [documentation](https://github.com/jpadilla/pyjwt/blob/master/docs/api.rst#L65)
This PR aims to bring everything in line.
I removed `bytes` from the type checking, but according to the test it was not handled (raising error [here](https://github.com/jpadilla/pyjwt/blob/master/jwt/api_jwt.py#L260)).
=> Update audience typing

jwt/api_jwk.py, tests/test_api_jwk.py
Hello :wave: 
This RP is intended to correct the problem related to issue #754.
I took the opportunity to add some typing and to simplify the testcase a bit.
I feel like we could also bring some key payload validation at the `PyJWK` constructor level (in another PR).
=> Improve PyJWKSet error accuracy

jwt/help.py, setup.cfg
This merge request:
1. Adds type hints to `jwt/help.py`
2. Adds `types-cryptography` to include types when installing.
=> Add type hints to jwt/help.py and add missing types dependency

.pre-commit-config.yaml, jwt/api_jws.py, jwt/help.py, jwt/utils.py, pyproject.toml, setup.cfg, tox.ini
Hello :wave: 
This RP is intended to solve the issue https://github.com/jpadilla/pyjwt/issues/745.
Moving the mypy check responsibility from tox env to pre-commit to reduce the feedback loop.
Moving config from `setup.cfg` to `pyproject.toml` to fit the new standard.
Thanks for the review :man_dancing:
=> Mypy as pre-commit check + api_jws typing

setup.cfg
This is not needed for using the project with `cryptography`. Also, the typing information is incorrect or incomplete for the latest version of `cryptography`.
Fixes #804
=> Remove `types-cryptography` from `crypto` extra

CHANGELOG.rst, jwt/api_jwt.py, tests/test_api_jwt.py
Handling 'ImmatureSignatureError' for issued_at time when it is a future time epoch.
```
if iat > (now + leeway):
raise ImmatureSignatureError("The token is not yet valid (iat)")
```
When the `issued_at` time in the payload is greater than the `current time + leeway` then we can call it out as `ImmatureSignatureError` as we do for `(nbf)`
We have `nbf` in the payload but still, with proper `nbf` someone can call the API with improper `iat` to fool the system.
Example:
```
{
"nbf": 1661419080   # 25-08-2022 14:48 IST
"iat": 1661419200,    # 25-08-2022 14:50 IST
"exp": 1661419500   # 25-08-2022 14:55 IST
}
```
Here the token is valid from 14:48(as per `nbf`) and has an expiry range of 5min from `iat` which makes the token valid. But the `iat` is less than `nbf` which makes the token valid …
=> Handling 'ImmatureSignatureError' for issued_at time

CHANGELOG.rst, setup.cfg
Some tools or services like https://pyreadiness.org/ use classifiers to check for compatibility with a particular Python version. It would be nice to have classifiers for all tested Python versions in `setup.cfg`.
=> Add classifier for Python 3.11

CHANGELOG.rst, docs/usage.rst, jwt/algorithms.py, tests/test_algorithms.py
`Algorithm.compute_hash_digest` is defined as a method which inspects the object to see that it has the requisite attributes, `hash_alg`.
If `hash_alg` is not set, then the method raises a NotImplementedError. This applies to classes like NoneAlgorithm.
If `hash_alg` is set, then it is checked for
```
has_crypto  # is cryptography available?
and isinstance(hash_alg, type)
and issubclass(hash_alg, hashes.HashAlgorithm)
```
to see which API for computing a digest is appropriate -- `hashlib` vs `cryptography.hazmat.primitives.hashes`.
These checks could be avoided at runtime if it were necessary to optimize further (e.g. attach compute_hash_digest methods to classeswith a class decorator) but this is not clearly a worthwhile optimization. Such perf tuning is intentionally omitted for now. …
=> Add `Algorithm.compute_hash_digest` and use it to implement at_hash validation example

jwt/api_jwt.py
=> fix: use datetime.datetime.timestamp function to have a milliseconds

CHANGELOG.rst, docs/usage.rst, jwt/algorithms.py, jwt/jwks_client.py, tests/test_jwks_client.py
Proposed change to address #822
=> Custom header configuration in jwk client

jwt/api_jwt.py, tests/test_compressed_jwt.py
This enables custom subclasses of `PyJWT` to customize decoding of the `payload` data of the JWS.
There's an example on how to subclass the function in the test case.
Refs #666 (reimplementation of it)
Refs #753 (reimplementation of it, borrows test case)
=> Add PyJWT._{de,en}code_payload hooks

jwt/api_jws.py, jwt/api_jwt.py, tests/test_api_jws.py
This allows you to not sort headers, which prevents a breaking change between v2.4.0 and v2.5.0
fixes https://github.com/jpadilla/pyjwt/issues/811
Should I create a unittest for this?
=> Add `sort_headers` parameter to `api_jwt.encode`

jwt/algorithms.py, jwt/jwk_set_cache.py, jwt/types.py
A few fixes I had while trying to fix https://github.com/jpadilla/pyjwt/issues/602.
I was also wondering if `Algorithm` could be made an abstract base class? Afaik it is not instanciated as is and this would avoid having to explicitly raise `NotImplementedError`.
Regarding https://github.com/jpadilla/pyjwt/issues/602, I might have a few solutions, but that might be tricky to handle (regarding the fact that `cryptography` is optional, as stated in https://github.com/jpadilla/pyjwt/pull/605). The least that can be done:
- Add types to the following methods for each algorithm: `prepare_key`, `sign` and `verify`.
- For the `Algorithm` methods, use a conditional Union including all available types, depending on the availability of `cryptography` (not sure if this will work as excepted).
- Use …
=> Add more types

CHANGELOG.rst, jwt/api_jwt.py
It's impossible to distinguish the two errors when 'audience' doesn't match.
The first error is programmer's fault – supplying an incorrect audience value.
The second is an expected error – when the audience doesn't match the required value.
The error messages shouldn't be the same.
=> Differentiate between two errors

jwt/api_jwk.py, tests/test_api_jwk.py
Fixes #820.
Maybe a warning could be added when iterating over the keys when we catch a `PyJWKSetError`?
=> Improve error messages when cryptography isn't installed

jwt/algorithms.py, jwt/api_jwt.py, tests/test_algorithms.py, tests/test_api_jws.py
Related: https://github.com/jpadilla/pyjwt/pull/843
=> Make `Algorithm` an abstract base class

CHANGELOG.rst
I believe there is a mistake in the changelog regarding the deprecated `verify=False` parameter.
When migrating from `pyjwt` version 1.7.1 to version 2.6.0, I noticed this line in the changelog:
>And the old v1.x syntax
>``jwt.decode(token, verify=False)``
>is now:
>``jwt.decode(jwt=token, key='secret', algorithms=['HS256'], options={"verify_signature": False, "verify_exp": True})``
However, when I examined the implementation, it seems that in version `1.7.1`, setting the `verify=False` parameter disables the timestamp verification. Hence, the equivalent to `verify=False` in version 2.x would just be ` options={"verify_signature": False}`.
This is also supported by a comment in `jwt/api_jwt.py:102`:
>"The verify argument to decode does nothing in PyJWT 2.0 and newer. "
>"The equivalent is …
=> docs: correct mistake in the changelog about verify param

jwt/jwks_client.py, tests/test_jwks_client.py
By default, the timeout for urlopen is socket._GLOBAL_DEFAULT_TIMEOUT which is None (meaning that the request never times out):
https://docs.python.org/3/library/socket.html#socket.getdefaulttimeout
This change sets the timeout to 30 but also adds a timeout variable users can set.
=> Add a timeout for PyJWKClient requests

jwt/exceptions.py, jwt/jwks_client.py, tests/test_jwks_client.py
This change adds a new `PyJWKClientConnectionError` exception which helps to differentiate connection errors from other types of failures when calling methods such as `get_signing_key_from_jwt()`. This allows users to do things like retry the method if there's a connection issue.
=> Add client connection error exception

.pre-commit-config.yaml, jwt/algorithms.py, jwt/api_jwk.py, jwt/api_jws.py, jwt/api_jwt.py, jwt/utils.py, pyproject.toml, tests/test_algorithms.py, tests/test_api_jws.py, tests/test_api_jwt.py, tests/test_utils.py
Fixes https://github.com/jpadilla/pyjwt/issues/602, https://github.com/jpadilla/pyjwt/issues/848, https://github.com/jpadilla/pyjwt/issues/856, https://github.com/jpadilla/pyjwt/issues/864#issuecomment-1458420475
I think this is the best we can get, without having to make use of `TypeVar`/`Generic` for algorithms. Had to tweak some parts to fix `mypy` errors.
One possible thing (as stated in https://github.com/jpadilla/pyjwt/pull/843) could be to add overloads to `encode`. I'll let you decide on this one, as it can hurt code readability.
Regarding the `decode` method, it can't be done as a list of allowed algorithms is passed.
=> Add complete types to take all allowed keys into account

.github/workflows/pypi-package.yml
Shamelessly copied from https://github.com/hynek/structlog/blob/main/.github/workflows/pypi-package.yml
All credit goes to @hynek
=> Build  and upload PyPI package

jwt/algorithms.py, pyproject.toml, setup.cfg, tests/test_algorithms.py
Fixes #880
This patch adds an optional `as_dict=False` keyword argument to `Algorithm.to_jwk()` functions.
Library API is still backwards compatible with this change: 
```
IPython 8.12.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import jwt
In [2]: algo = jwt.get_algorithm_by_name('HS256')
In [3]: jwk_json = algo.to_jwk('test')
In [4]: type(jwk_json), jwk_json
Out[4]: (str, '{"k": "dGVzdA", "kty": "oct"}')
In [5]: jwk_dict = algo.to_jwk('test', as_dict=True)
In [6]: type(jwk_dict), jwk_dict
Out[6]: (dict, {'k': 'dGVzdA', 'kty': 'oct'})
```
=> Add `as_dict` option to `Algorithm.to_jwk`

.github/workflows/main.yml, .github/workflows/pypi-package.yml, .pre-commit-config.yaml, jwt/algorithms.py, jwt/api_jwk.py, setup.cfg, tests/test_api_jwt.py, tox.ini
The [Python 3.12 release candidate is out!](https://discuss.python.org/t/python-3-12-0-release-candidate-1-released/31137?u=hugovk) :rocket:
> ## Call to action
> 
> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.12 compatibilities during this phase, and where necessary publish Python 3.12 wheels on PyPI to be ready for the final release of 3.12.0.
Also:
* Drop support for EOL Python 3.7: https://devguide.python.org/versions/
* Upgrade syntax with [pyupgrade](https://github.com/asottile/pyupgrade) --py38-plus
* Only attempt deploy for upstream, otherwise it fails for forks due to missing credentials
=> Add support for Python 3.12

jwt/api_jwt.py
Just something I noticed while checking behavior -- an unnecessary str concat.
This was likely introduced by `black`ening the code. It's a non-issue but "looks weird" and something I like to weed out from my own projects.
I have [a linter](https://github.com/sirosen/dotfiles/blob/04bf5f8/bin/bin/check-bad-str-concat) I keep around for exactly this issue, and it runs successfully after this change, so we can be confident that this is the only case of this.
=> Fix an unnecessary str concat

jwt/api_jwt.py, tests/test_api_jwt.py
This diff updates jwt issuer validation to accept either a string (as it always has) or a `List[str]`, and consideres the jwt `iss` claim valid if the single string matches or if `jwt[iss]` is found in the list.  Method signatures should be unchanged, though types were updated.
=> Update jwt-api to accept either a string or list of strings for issuer validation

jwt/utils.py, tests/test_utils.py
After looking though `cryptography`'s code, checking if the key starts with the 6 known types is enough here.
=> Add coverage and improve performance of is_ssh_key

docs/usage.rst, jwt/api_jwk.py, jwt/api_jws.py, jwt/api_jwt.py, tests/test_api_jwk.py, tests/test_api_jws.py
This PR contains three proposed changes.  You can accept or reject any of them as you see fit.  This is just a rough draft, once the functionality is approved I'll clean it up, add tests, and document.
1) Add `algorithm` string to `PyJWK`.  This is useful in determine the appropriate `algorithms` value to pass into `decode()`.
2) Allow a `PyJWK` to be passed directly into `decode()`, so it's not necessary to pull `PyJWK.key`.  (This would fix #864)
3) If a `PyJWK` is passed into `decode()` and `algorithms` is not set, use the algorithm from the JWK.  This change makes the API more convenient and reduces room for error:  There's no reason that you should use any algorithm *but* the JWK's algorithm and doing otherwise is problematic at best and a possible security threat at worst.
=> Decode with PyJWK

docs/usage.rst
Since `kid` is not used in the example code for "Retrieve RSA signing keys from a JWKS endpoint", I removed it to avoid any potential confusion.
=> Remove an unused variable from an example code block

jwt/algorithms.py, tests/test_algorithms.py
This is a stab at addressing the issue discussed here: [Consider cryptography 42.x.x new validation #948](https://github.com/jpadilla/pyjwt/issues/948)
All I did is raise a `InvalidKeyError` when there is a ValueError and `return cast(RSAPublicKey, load_pem_public_key(key_bytes))` fails.
fix https://github.com/jpadilla/pyjwt/issues/948
=> Handle load_pem_public_key ValueError

jwt/api_jwk.py, jwt/exceptions.py, tests/test_api_jwk.py
We recently ran into this when deploying an app with Docker. Locally everything worked fine but the dependency was missing in the container's environment. We had seen the note about it in the docs, but (wrongly) assumed that pyjwt would complain if it tried to use the missing dependency.
My hope with this PR is that it might prevent other people from being stuck on this in the future.
=> Raise exception when required cryptography dependency is missing

CHANGELOG.rst, jwt/api_jws.py, jwt/api_jwt.py
this loosens up the typing for `issuers` & `algorithms` in the API
there's no reason we need to use `List` for the typing of issuers & other parameters - the `Sequence` type allows us to accept more types such as `tuple` and `set` which still support the behavior we need
=> chore: use sequence for typing rather than list

.github/workflows/main.yml, setup.cfg, tox.ini
The Python 3.13 release candidate is out now! :rocket:
The Release Manager has issued a [call to action](https://discuss.python.org/t/python-3-13-0-release-candidate-1-released/59703?u=hugovk]):
> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.13 compatibilities during this phase, and where necessary publish Python 3.13 wheels on PyPI to be ready for the final release of 3.13.0. Any binary wheels built against Python 3.13.0rc1 **will work** with future versions of Python 3.13. As always, report any issues to [the Python bug tracker](https://github.com/python/cpython/issues).
=> Add support for Python 3.13

.readthedocs.yaml, MANIFEST.in, tox.ini
The documentation has been [failing to build on Read the Docs for a very long time](https://readthedocs.org/projects/pyjwt/builds/). The builds are failing for lack of a mandatory RTD configuration file ([link to final build attempt from 7 months ago](https://readthedocs.org/projects/pyjwt/builds/22963746/)).
This PR introduces a preliminary RTD config file.
----
Separately, I recommend changing the badge in the README, as well, so that it's more apparent when documentation builds are failing. Currently the docs badge is pointing to 'stable', but if it had pointed to 'latest' it would have been much more visible that builds have been failing.
* 'stable' badge currently in README:
```
https://readthedocs.org/projects/pyjwt/badge/?version=stable
```
* 'latest' badge recommendation:
``` …
```
=> Add an RTD config file to resolve RTD build failures

docs/api.rst
Updating documentation given which exception is thrown when. Source: https://github.com/jpadilla/pyjwt/blob/d7710f7bcff4b195b293af554a32d4a461b07a01/jwt/api_jwt.py#L268-L279
=> docs: Update `iat` exception docs

CHANGELOG.rst, jwt/api_jwt.py
Followup on #886.  Although I updated the JWS API, the JWT API independently requires a non-empty algorithms list.  This PR just removes that enforcement entirely—We can rely on the JWS API to make sure an appropriate algorithms list is passed in.
=> Remove algorithm requirement for JWT API

tests/test_utils.py
See https://docs.pytest.org/en/stable/example/parametrize.html#parametrizing-conditional-raising. We should be "passing" the test if the correct action is to raise a ValueError.
=> fix test_utils.py not to xfail

docs/api.rst
As title, correcting the `audience` parameter type expression in the `jwt.decode` method.
Before:
After:
=> Correct jwt.decode audience param doc expression

CHANGELOG.rst, jwt/api_jws.py, jwt/api_jwt.py, tests/test_api_jws.py
To round out my contributions, this PR adds JWK support to `api_jws.encode` and `api_jwt.encode`.
Most significant change is change of default algorithm to `DEFAULT_ALGORITHM`.  This will resolve to the JWK algorithm if applicable, otherwise `HS256`.
=> Add JWK support to JWT encode

.github/workflows/enforce-changelog-entry.yml, .pre-commit-config.yaml, CHANGELOG.rst
Include checkers and linters for the `pyproject.toml`  and `yaml` configuration files
Follow up to #995 to ensure PEP-517/PEP-518 conformance
=> Update pre-commit hooks to lint pyproject.toml

docs/usage.rst
closes #989 
- This PR adds ES256 (ECDSA) algorithm usage accordingly with working key pairs.
=> Add ES256 usage 

CHANGELOG.rst, jwt/algorithms.py, jwt/utils.py
Closes #709 and #925
An optional `bit_length` field is added to `utils.bytes_from_int` and `utils.to_base64url_uint`. This is used to encode the EC JWK fields `x`, `y`, and `d` to a fixed byte length.
Prior to this change, the encoded byte length was variable, but the JWK validator required it to be fixed.
=> Encode EC keys with a fixed bit length

.github/workflows/main.yml, .pre-commit-config.yaml, CHANGELOG.rst, pyproject.toml, ruff.toml, tox.ini
With the release of Python 3.13, Python 3.8 is now end of life, as shown on https://devguide.python.org/versions/
By dropping Python 3.8, this expands the available features for unconditional use in the library to include (but is not limited to):
- [Dictionary merge and update operators](https://docs.python.org/3/whatsnew/3.9.html#dictionary-merge-update-operators)
- [Type Hinting Generics in Standard Collections](https://docs.python.org/3/whatsnew/3.9.html#type-hinting-generics-in-standard-collections)
- [New string methods to remove prefixes and suffixes](https://docs.python.org/3/whatsnew/3.9.html#new-string-methods-to-remove-prefixes-and-suffixes)
- [`hashlib` now can use SHA3 and SHAKE XOF from OpenSSL](https://docs.python.org/3/whatsnew/3.9.html#hashlib)
- [`typing.Annotated` is now …
=> Drop support for Python 3.8

CHANGELOG.rst, README.rst, SECURITY.md, docs/index.rst, jwt/__init__.py
Hi @jpadilla  and @auvipy ,
As there were some features currently merged to the master branch (i.e. mostly the `sub` and `jti` validation functionality), that were not part of a release yet, I thought I'd update the Changelog again.
I was not sure whether the example on the `"none"` algorithm should stay as part of the Changelog, or should move to `usage.rst` for now I just added some context on where it was introduced.
In case any changes are required, please let me know, I have some time work on this.
As I saw the CI was failing on how the Auth0 logo, I re-arranged the code a bit in README.rst, which fixed the pyroma RST linting errors. The logo still works. Also I fixed various other RST related issues.
=> Prepare 2.10.0 release

CHANGELOG.rst, docs/api.rst, docs/conf.py, jwt/algorithms.py, jwt/api_jwk.py, jwt/api_jws.py, jwt/api_jwt.py, jwt/exceptions.py, jwt/types.py, pyproject.toml, tests/test_api_jwt.py
Basically trying to remove "Unknown" or "partially unknown" pylance issues. Mostly with `options`, but there were a few simple other fixes (kwargs, segments, etc). This showed some minor bugs and a few code smells (passing too many args to `api_jws.decode_complete`, for example).
=> Fixes #660: Improve typing/logic for `options` in decode, decode_complete; Improve docs

jwt/api_jws.py, jwt/api_jwt.py
Reverts the changes introduced in #979, fixing #1022.
=> Fix #1022: Map `algorithm=None` to "none"

jwt/api_jwt.py
Fixed docstring typo 
```
def _validate_jti(self, payload: dict[str, Any]) -> None:
'''
Checks whether "jti" if in the payload is valid **or** not
This is an Optional claim
:param payload(dict): The payload which needs to be validated
'''
```
```
def _validate_jti(self, payload: dict[str, Any]) -> None:
'''
Checks whether "jti" if in the payload is valid **ot** not
This is an Optional claim
:param payload(dict): The payload which needs to be validated
'''
```
=> Fixed doc string typo in _validate_jti() function #1063

docs/usage.rst
Hey, spent half an hour while debugging why my token for APNS is not the same length like generated from apple :) And finally found, that in my token header "typ": "JWT" is included by default, so probably it will be good to reflect this in documentation :)
=> Fix TYP header documentation

CHANGELOG.rst, docs/usage.rst, jwt/algorithms.py
Document the `sub` and `jti` claims.
The `sub` claim is referenced in the documentation, but was not documented as a registered claim name. 
The `jti` claim is useful to document to prevent replay attacks.
Now all registered claim names are documented for completeness.
=> doc: Document claims sub and jti
