tests/test_jwt.py

Avoid ResourceWarning in tests

---

jwt/__init__.py

Drop unneeded **kwargs magic

---

jwt/__init__.py

Verify that decoded header and payload are json objects

---

jwt/__init__.py
jwt/compat.py

Handle compatibility branching in a compat module

---

README.md

The title says it all. Fixes #80 and addresses the concerns from #81.

Updated documentation to match the latest version of the JWT specification (draft 32)

---

MANIFEST.in

The terms of the license say that you have to...
https://github.com/jpadilla/pyjwt/blob/master/LICENSE#L12-L13

Include LICENSE and AUTHORS in the release tarball

---

README.md
jwt/algorithms.py

Fixed some DeprecationWarnings related to our cryptography 0.8 upgrade and updated the README to make sure users have at least 0.8 of cryptography.

Fixed some DeprecationWarnings related to our cryptography 0.8 upgrade

---

jwt/api.py
tests/test_api.py

Moved claims validation into a separate private method to make it simpler to understand the code.

Moved claims validation into a separate private method to make it simpler to understand the code.

---

jwt/api.py
jwt/utils.py
tests/test_algorithms.py
tests/test_api.py

* Changed PyJWT.default_options to PyJWT.options; made it a little more private as well
* Optimized _merge_options and changed some variable names
* Created merge_dict utility function in utils
* Added a test to improve coverage and cleaned up some existing tests.

Minor refactorings to make things a little cleaner

---

.coveragerc
setup.cfg
setup.py
tests/compat.py
tests/contrib/test_algorithms.py
tests/test_algorithms.py
tests/test_api.py
tests/test_compat.py
tests/test_jwt.py
tests/utils.py
tox.ini

Resolves #111 
* Installed Pytest
* Converted all unittest-related assertions to normal `assert` statements
* Removed all references to unittest from the project

Changed to use Pytest as the test runner #111

---

CHANGELOG.md
jwt/__init__.py
jwt/api_jws.py
jwt/api_jwt.py
tests/test_api_jws.py

Added get_unverified_header method so that unverified headers can be retrieved by the application. Closes #155

Added get_unverified_header method

---

CHANGELOG.md
jwt/__init__.py

Time to do another release since we've had so many bugfixes (mainly RSA-PSS and ECDSA being fixed)
cc: @jpadilla

Preparing for 1.3 release

---

jwt/api_jws.py
tests/test_api_jws.py

Fixed #167 throw InvalidAlgorithmError if alg not in header

---

setup.py

Based on instructions on pytest-runner: https://bitbucket.org/pytest-dev/pytest-runner

Made pytest-runner installation in setup.py conditional. Fixes #179

---

docs/faq.rst

Update FAQ to clarify Python2/3 differences

---

CHANGELOG.md
jwt/__init__.py

v1.5.0 release

---

README.rst
docs/index.rst
docs/requirements-docs.txt

Added Command line instructions to README and docs #259

---

.travis.yml
setup.py
tox.ini

Fixes #418
Related: [mypy no longer supports running on Python 3.4](https://github.com/python/mypy/issues/6564)

Run mypy with tox

---

codecov.yml
jwt/__init__.py

Although I still need to go update docs and changelog. I'm thinking we can just do some pre-releases in the meantime. Thoughts @auvipy?

Update version to 2.0.0a1

---

docs/usage.rst

The algorithms parameter for decode accepts list not a string.

Fix usage example

---

jwt/algorithms.py
jwt/api_jws.py
jwt/api_jwt.py

- Remove "noqa" comments that are unnecessary
- Remove unused imports from api_jwt.py

Cleanup "noqa" comments

---

jwt/api_jws.py
jwt/api_jwt.py

In Python 3, these values will always be str.

Tighten type checking of string values

---

tests/test_jwks_client.py

No need to create a fixture with a nested function. This can be a simple
utility function.

Simplify mocked_response test utility function

---

.pre-commit-config.yaml
docs/usage.rst

https://pre-commit.com/#updating-hooks-automatically

Autoupdate pre-commit hooks and apply them

---

setup.cfg

Update requirement on `cryptography`

---

docs/algorithms.rst

Sorry. I forgot to update the document for ES256K.

Update doc for ES256K.

---

CHANGELOG.rst
jwt/__init__.py

Export PyJWK and PyJWKSet

---

LICENSE
docs/conf.py
jwt/__init__.py

Fix: #458
Updates the copyright information to be a range not a single date.

fix: Update copyright information

---

jwt/api_jwt.py
tests/test_api_jwt.py

Revert "adding support for compressed payloads"

---

setup.cfg

https://github.com/jpadilla/pyjwt/issues/804#issuecomment-1251238516

bump up cryptography >= 3.4.0

---

CHANGELOG.rst
jwt/api_jwt.py

Closes https://github.com/jpadilla/pyjwt/issues/796

Invalidate exp when exp == now()

---

CHANGELOG.rst
jwt/api_jwt.py
tests/test_api_jwt.py

Fix `_validate_iat` validation

---

docs/api.rst

See https://github.com/jpadilla/pyjwt/pull/902#issuecomment-1751684349.

docs/api: document strict_aud on decode_complete

---

docs/usage.rst

In the Usage > OIDC Login Flow section:
- Fixed the scope for decode_complete()
- Added algorithms argument to the call

docs fix: decode_complete scope and algorithms

---

docs/usage.rst
tox.ini

Breaking CI checks for #985, and probably `master` branch CI checks.

fix doctest for docs/usage.rst

---

docs/usage.rst

As title, adding the `PS256` encoding and decoding usage in the documentation.

Add PS256 encoding and decoding usage

---

CHANGELOG.rst
docs/usage.rst

Leeway is also implemented for the nbf claim.  Add documentation on using leeway with nbf, and why it could be necessary.

Make note of use of leeway with nbf

---

CHANGELOG.rst
jwt/api_jwk.py
tests/test_api_jwk.py

Opening a sample PR for the change, based on @Kyle-sandeman-mrdfood's proposal in the GH issue.

Feat #1024: Add iterator for PyJWKSet

---

CHANGELOG.rst
jwt/api_jwt.py
tests/test_api_jwt.py

Fixes #1039: Add iss, issuer type checks

---

jwt/jwks_client.py

Fixes #1047: Correct `PyJWKClient.get_signing_key_from_jwt` annotation 
